name: Renovate
on:
  workflow_dispatch: {}
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v31.21.0
        env:
          LOG_LEVEL: debug
        with:
          configurationFile: .renovaterc.json
          token: ${{ secrets.RENOVATE_TOKEN }}
